-- Additional BambooHR orgs for Afrorama
-- Run in Supabase SQL Editor → New Query

INSERT INTO bamboohr_orgs (subdomain, name, country, sector) VALUES
  ('350',                    '350.org',                                  'KE', 'Climate & Environment'),
  ('actionaidinternational', 'ActionAid International',                  'ZA', 'Human Rights'),
  ('actionaidzimbabwe',      'ActionAid Zimbabwe',                       'ZW', 'Human Rights'),
  ('aflatoun',               'Aflatoun International',                   'KE', 'Education'),
  ('africanclimatefoundation','African Climate Foundation',              'ZA', 'Climate & Environment'),
  ('africapractice',         'Africa Practice',                          'KE', 'Governance & Public Policy'),
  ('bfaglobal',              'BFA Global',                               'KE', 'Finance & Economics'),
  ('bhrrc',                  'Business & Human Rights Resource Centre',  'ZA', 'Human Rights'),
  ('bridgestoprosperity',    'Bridges to Prosperity',                    'RW', 'Infrastructure & Urban Development'),
  ('c40',                    'C40 Cities',                               'ZA', 'Climate & Environment'),
  ('caribou',                'Caribou Digital',                          'KE', 'Innovation & Technology'),
  ('civilians',              'Center for Civilians in Conflict',         'KE', 'Human Rights'),
  ('clear',                  'CLEAR Francophone Africa',                 'SN', 'Governance & Public Policy'),
  ('climatefundmanagers',    'Climate Fund Managers',                    'ZA', 'Climate & Environment'),
  ('culturalsurvival',       'Cultural Survival',                        'KE', 'Human Rights'),
  ('delta40',                'Delta40',                                  'ZA', 'Finance & Economics'),
  ('developmentmedia',       'Development Media International',          'ZA', 'Governance & Public Policy'),
  ('dial',                   'Digital Impact Alliance',                  'KE', 'Innovation & Technology'),
  ('dtree',                  'D-Tree International',                     'TZ', 'Health'),
  ('ejscenter',              'EJS Center',                               'ZA', 'Human Rights'),
  ('equalitynow',            'Equality Now',                             'KE', 'Gender & Social Inclusion'),
  ('firelightfoundation',    'Firelight Foundation',                     'ZA', 'Education'),
  ('fosfeminista',           'Fos Feminista',                            'KE', 'Gender & Social Inclusion'),
  ('foundervine',            'FounderVine',                              'GH', 'Innovation & Technology'),
  ('globalfundforwomen',     'Global Fund for Women',                    'KE', 'Gender & Social Inclusion'),
  ('globalinitiative',       'Global Initiative Against Transnational Organized Crime', 'ZA', 'Human Rights'),
  ('greenco',                'Greenco',                                  'ZA', 'Climate & Environment'),
  ('gwpsanpc',               'Global Water Partnership Southern Africa', 'ZA', 'Climate & Environment'),
  ('hotosm',                 'Humanitarian OpenStreetMap Team',          'KE', 'Innovation & Technology'),
  ('ibis',                   'Ibis',                                     'KE', 'Human Rights'),
  ('ibp',                    'International Budget Partnership',         'ZA', 'Finance & Economics'),
  ('idc',                    'IDC',                                      'ZA', 'Finance & Economics'),
  ('iisd',                   'International Institute for Sustainable Development', 'KE', 'Climate & Environment'),
  ('internetsociety',        'Internet Society',                         'KE', 'Innovation & Technology'),
  ('itadltd',                'ITAD Ltd',                                 'ZA', 'Governance & Public Policy'),
  ('jsheld',                 'JS Held',                                  'ZA', 'Governance & Public Policy'),
  ('leadforghana',           'Lead for Ghana',                           'GH', 'Education'),
  ('legalactionworldwide',   'Legal Action Worldwide',                   'KE', 'Human Rights'),
  ('lminternational',        'LM International',                         'ZA', 'Governance & Public Policy'),
  ('luminate',               'Luminate',                                 'KE', 'Governance & Public Policy'),
  ('mainstreamrp',           'Mainstream Renewable Power',               'ZA', 'Climate & Environment'),
  ('malalafund',             'Malala Fund',                              'KE', 'Education'),
  ('meda',                   'MEDA',                                     'KE', 'Finance & Economics'),
  ('mertechservices',        'MerTech Services',                         'ZA', 'Innovation & Technology'),
  ('miraclefeet',            'MiracleFeet',                              'ZA', 'Health'),
  ('mpharma',                'mPharma',                                  'GH', 'Health'),
  ('msfsa',                  'Médecins Sans Frontières SA',              'ZA', 'Health'),
  ('niyel',                  'Niyel',                                    'SN', 'Governance & Public Policy'),
  ('nonviolentpeaceforce',   'Nonviolent Peaceforce',                    'SS', 'Human Rights'),
  ('precisiondev',           'Precision Development',                    'KE', 'Agriculture & Food Security'),
  ('refugeeledresearchhub',  'Refugee-Led Research Hub',                 'KE', 'Human Rights'),
  ('restlessdevelopment',    'Restless Development',                     'TZ', 'Governance & Public Policy'),
  ('ri',                     'Relief International',                     'KE', 'Human Rights'),
  ('seedglobal',             'Seed Global Health',                       'ZA', 'Health'),
  ('sistemaaccount',         'Sistema B',                                'ZA', 'Finance & Economics'),
  ('solidaridadnetworkeca',  'Solidaridad Network East & Central Africa','KE', 'Agriculture & Food Security'),
  ('sparkmicrogrants',       'Spark MicroGrants',                        'RW', 'Finance & Economics'),
  ('strongminds',            'StrongMinds',                              'UG', 'Health'),
  ('teachingattherightlevel','Teaching at the Right Level Africa',       'KE', 'Education'),
  ('thousandcurrents',       'Thousand Currents',                        'KE', 'Finance & Economics'),
  ('togetherforgirls',       'Together for Girls',                       'KE', 'Gender & Social Inclusion'),
  ('triggerise',             'Triggerise',                               'ZA', 'Health'),
  ('trustafrica',            'TrustAfrica',                              'SN', 'Finance & Economics'),
  ('upenergygroup',          'Up Energy Group',                          'KE', 'Climate & Environment'),
  ('vilcap',                 'Village Capital',                          'KE', 'Finance & Economics'),
  ('witness',                'WITNESS',                                  'ZA', 'Human Rights'),
  ('wusc',                   'WUSC',                                     'KE', 'Education'),
  -- New additions
  ('livinggoods',            'Living Goods',                              'KE', 'Health'),
  ('sanergy',                'Sanergy',                                   'KE', 'Infrastructure & Urban Development'),
  ('camfed',                 'CAMFED',                                    'ZW', 'Education'),
  ('vsointernational',       'VSO International',                         'KE', 'Governance & Public Policy'),
  ('gainhealth',             'GAIN',                                      'KE', 'Agriculture & Food Security'),
  ('engie-energy-access',    'ENGIE Energy Access',                       'KE', 'Climate & Environment'),
  ('opportunityintl',        'Opportunity International',                  'KE', 'Finance & Economics'),
  ('rti',                    'RTI International',                         'KE', 'Governance & Public Policy'),
  ('givepower',              'GivePower',                                 'KE', 'Climate & Environment'),
  ('fsdafrica',              'FSD Africa',                                'KE', 'Finance & Economics'),
  ('amrefhealthafrica',      'Amref Health Africa',                       'KE', 'Health'),
  ('sunking',                'Sun King',                                  'KE', 'Climate & Environment'),
  ('landesa',                'Landesa',                                   'KE', 'Governance & Public Policy'),
  ('tahmo',                  'TAHMO',                                     'GH', 'Climate & Environment'),
  ('dalberg',                'Dalberg',                                   'KE', 'Governance & Public Policy'),
  ('laterite',               'Laterite',                                  'RW', 'Governance & Public Policy'),
  ('busara',                 'Busara Center',                             'KE', 'Governance & Public Policy'),
  ('resonance',              'Resonance',                                 'KE', 'Governance & Public Policy'),
  ('morningside',            'Morningside Group',                         'ZA', 'Finance & Economics')
ON CONFLICT (subdomain) DO NOTHING;
